#!/bin/bash

while true; do
    boost=$(cpufreqctl --boost)
    status=$(cat /sys/class/power_supply/BAT0/status)
    if [[ $status == "Discharging" ]] && [[ $boost == "0" ]]
    then
        echo "Boost enabled"
        boost=1
        cpufreqctl --boost --set=1
    elif [[ $status == "Charging" ]] && [[ $boost == "1" ]]
    then
        boost=0
        echo "Boost disabled"
        cpufreqctl --boost --set=0
    elif [[ $status == "Full" ]] && [[ $boost == "1" ]]
    then
        boost=0
        echo "Boost disabled"
        cpufreqctl --boost --set=0
    fi 
    sleep 5
done
