#!/bin/bash

while true; do
    boost=$(cat /sys/devices/system/cpu/cpufreq/boost)
    status=$(cat /sys/class/power_supply/BAT0/status)
    if [[ $status == "Discharging" ]] && [[ $boost == "0" ]]
    then
        echo "Boost enabled"
        boost=1
        /home/uroborosq/Рабочий\ стол/Linux/cmd/bin/boost-cli on
    elif [[ $status == "Charging" ]] && [[ $boost == "1" ]]
    then
        boost=0
        echo "Boost disabled"
        /home/uroborosq/Рабочий\ стол/Linux/cmd/bin/boost-cli off
    elif [[ $status == "Full" ]] && [[ $boost == "1" ]]
    then
        boost=0
        echo "Boost disabled"
         /home/uroborosq/Рабочий\ стол/Linux/cmd/bin/boost-cli off
    fi 
    sleep 5
done
