#!/bin/bash

current_workspace=$(hyprctl activeworkspace -j | jq -r '.id')
windows=$(hyprctl clients -j | jq -r --argjson ws "$current_workspace" '.[] | select(.workspace.id == $ws and .grouped == []) | .address')

hyprctl dispatch togglegroup

if [[ ${#windows[@]} -eq 0 ]]; then
    exit 0
fi

for window in $windows; do
    hyprctl dispatch focuswindow address:"$window"
    hyprctl dispatch moveintogroup l
    hyprctl dispatch moveintogroup u
    hyprctl dispatch moveintogroup d
    hyprctl dispatch moveintogroup r

done
