#!/bin/bash

paru -S azote nwg-drawer-bin nwg-bar-bin xdg-desktop-portal-wlr grim slurp jq grimshot mako waybar wl-clipboard wlr-randr wofi wob swayidle sway kwallet polkit-gnome dex pamixer ncpamixer swaybg swayidle light kwallet-pam wmname network-manager-applet kanshi swaylock-effects ydotool xorg-xwayland
