#!/bin/env bash

source <(dbus-launch)

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

systemd-cat -t sway sway "$@" --unsupported-gpu 2>&1
