#!/bin/zsh

nvim ~/.config/sway/config \
    ~/.config/waybar/config.json \
    ~/.config/waybar/style.css \
    ~/.config/kitty/kitty.conf \
    ~/.config/mako/config \
    ~/.config/wofi/style.css \
    ~/.config/wob/wob.ini
