#!/bin/zsh

xdg-open ~/.config/sway/config  ~/.config/waybar/config ~/.config/waybar/style.css  ~/.config/alacritty/alacritty.yml  ~/.config/mako/config  ~/.config/wofi/style.css ~/.config/wob/wob.ini
exit
