#!/bin/bash

Green='\033[0;32m'
Default='\033[0m'
ICyan='\033[0;96m'

echo -e "${Green}Welcome to the UroborosQ's update script!${Default}"

echo -e "${ICyan}paru updating...${Default}"

paru

#flatpak update

if [[ -f /usr/bin/flatpak ]]; then

	echo -e "${ICyan}flatpak updating...${Default}"
	flatpak update
fi

current_directory=$(pwd)

cd -- "$HOME"/apps || (echo "no ~/apps directory!" && exit)

echo -e "${ICyan} git apps updating...${Default}"

for DIR in *; do
	echo -e "${Green} updating $DIR${Default}"
	cd "$DIR" || continue
	[[ -d .git ]] && git pull || echo "no git repo!"
	cd ..
done

cd -- "$current_directory" || exit

echo -e "${ICyan} go binaries updating...${Default}"

go install github.com/Gelio/go-global-update@latest

go-global-update
