#!/bin/bash

Green='\033[0;32m'
Cyan='\033[0;36m'  
Default='\033[0m'  
ICyan='\033[0;96m' 

echo -e  "${Green}Welcome to the UroborosQ's update script!${Default}"

echo -e "${ICyan}paru updating...${Default}"

paru

#flatpak update

if [[ -f /usr/bin/flatpak ]]; then

	echo -e "${ICyan}flatpak updating...${Default}"
	flatpak update
fi

current_directory=$(pwd)











cd -- "$current_directory"
