os:
  open: 'nvim --server "$NVIM" --remote-send "<C-L>"  && nvim --server "$NVIM" --remote-send ":e {{filename}}<CR>" && nvim --server "$NVIM" --remote-send "<C-W>wq"'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
